### PR TITLE
review en-us docker-deployment.md

### PR DESCRIPTION
**Pull request by Tianqi-Dotes**

### CODE REVIEW

**Comment by CalvinKirs** [comment]
@ptyp @Segun-Ogundipe PTAL.Thx  (chinese doc：https://github.com/apache/incubator-dolphinscheduler-website/blob/master/docs/zh-cn/1.3.4/user_doc/docker-deployment.md）

**Review by Segun-Ogundipe — APPROVED** [review]
LGTM

**Comment by CalvinKirs** [comment]
> LGTM

Thx

**Review by break60 — APPROVED** [review]
+1

**Review by dailidong — APPROVED** [review]
+1
good job

**Pull request merged**
