### PR TITLE
remove online demo table in the navigation bar

### PR DESCRIPTION
**Pull request by aNotBadCoder**
Please review #249

### CODE REVIEW

**Review by break60 — APPROVED** [review]
+1

**Review by dailidong — APPROVED** [review]
+1
good job

**Comment by chengshiwen** [comment]
@aybcoo Please check:
- [docs.js#L98](https://github.com/apache/incubator-dolphinscheduler-website/blob/e962bdfcd7f25c74ff9ac74f5a1aa46057fce8c8/site_config/docs.js#L98)
- [site.js#L66](https://github.com/apache/incubator-dolphinscheduler-website/blob/e962bdfcd7f25c74ff9ac74f5a1aa46057fce8c8/site_config/site.js#L66)

**Comment by aybcoo** [comment]
@chengshiwen I will fix it ，Thank you！

**Comment by aybcoo** [comment]
> @aybcoo Please check again:
> 
> * [docs.js#L93](https://github.com/apache/incubator-dolphinscheduler-website/blob/e962bdfcd7f25c74ff9ac74f5a1aa46057fce8c8/site_config/docs.js#L93)
> * [site.js#L63](https://github.com/apache/incubator-dolphinscheduler-website/blob/e962bdfcd7f25c74ff9ac74f5a1aa46057fce8c8/site_config/site.js#L63)

@chengshiwen  https://github.com/apache/incubator-dolphinscheduler-website/pull/251

**Pull request merged**
