### PR TITLE
WebsiteDocs-3: Added the English 'development-environment-setup' mark…

### PR DESCRIPTION
**Pull request by IamMujuziMoses**
…down which was present in Chinese but wasn't present in English and how to access it in 'development.js' file

### CODE REVIEW

**Comment by IamMujuziMoses** [comment]
This PR is associated to this main [issue]

[issue]: https://github.com/apache/incubator-dolphinscheduler/issues/3562

**Comment by CalvinKirs** [comment]
@Segun-Ogundipe @Tianqi-Dotes PTAL.Thx

**Comment by Segun-Ogundipe** [comment]
Hi @CalvinKirs, the issue this PR is for has another PR that has been merged already. Should this still be reviewed or is the issue closed?

**Comment by CalvinKirs** [comment]
> Hi @CalvinKirs, the issue this PR is for has another PR that has been merged already. Should this still be reviewed or is the issue closed?

Sorry, this is my negligence

**Comment by CalvinKirs** [comment]
Hi, thank you very much for your contribution, but this piece of content has been contributed and merged before. The content you have done is duplicate, you can update the latest code to check, after that, this PR will be closed, you can check the previous PR to see if you need to modify it, thank you very much

**Pull request closed without merging**
