### PR TITLE
change node version from 8 to 10.

### PR DESCRIPTION
**Pull request by Yibo-Liu**
According to github readme.md, change website node version from 8 to 10.

### CODE REVIEW

**Comment by dailidong** [comment]
good job
@break60 please review this PR if you free

**Comment by break60** [comment]
Should be changed to 8.X-10.x, the old version currently supports up to 10.X version

**Comment by Yibo-Liu** [comment]
@break60 emm, sorry I can't understand what you mean. Do you mean I should change the word in my PR's  from "10.x" to "8.X-10.x" ?

**Review by break60 — APPROVED** [review]
+1

**Comment by break60** [comment]
> @break60 emm, sorry I can't understand what you mean. Do you mean I should change the word in my PR from "10.x" to "8.X-10.x" ?

sorry, I see it as the front-end document of ds

**Review by dailidong — APPROVED** [review]
+1
good job, looking forward to your deep participation

**Pull request merged**
