### PR TITLE
WebsiteDocs-2: Added The English 'commit_message' markdown which was …

### PR DESCRIPTION
**Pull request by IamMujuziMoses**
…preent in Chinese but wasn't present in English and how to access it in the 'development.js' file

### CODE REVIEW

**Comment by IamMujuziMoses** [comment]
This PR is associated to this main [issue]

[issue]: https://github.com/apache/incubator-dolphinscheduler/issues/3562

**Comment by CalvinKirs** [comment]
good job! @Segun-Ogundipe @Tianqi-Dotes PTAL.Thx

**Comment by Segun-Ogundipe** [comment]
@CalvinKirs, the issue linked to this PR has been fixed by another PR, which has since been merged
 Is there still any need to review this?

**Comment by CalvinKirs** [comment]
Hi, thank you very much for your contribution, but this piece of content has been contributed and merged before. The content you have done is duplicate, you can update the latest code to check, after that, this PR will be closed, you can check the previous PR to see if you need to modify it, thank you very much

**Pull request closed without merging**
