### PR TITLE
fix the issue:The professional vocabulary is misspelled

### PR DESCRIPTION
**Pull request by heyzeng**
The professional vocabulary is misspelled on the Official website of dolphinscheduler.For example, MySQL is written as Mysql,ZooKeeper is writtern as zookeeper.
image

### CODE REVIEW

**Comment by heyzeng** [comment]
can you merge this pr? thank you!

**Comment by break60** [comment]
@dailidong

**Comment by heyzeng** [comment]
I fixed the conflict，can you review it?

**Comment by dailidong** [comment]
thanks for your first contribution, looking forward for next participation,  if you need help, please send mail to dev@dolphinscheduler.apache.org or you can add my wechat(510570367), when added, please tell me you are heyzeng

**Pull request merged**
